### PR TITLE
Publish to PyPI for Easier Distribution and Use

### PR DESCRIPTION
**Pull request by 16BitS3G4l**
After a few simple commits, this repo has been *unofficially* published on PyPI(addressing issue #7)

### CODE REVIEW

**Comment by 343max** [comment]
Thank you!

**Comment by 343max** [comment]
Is there something else I need to do?

**Comment by 16BitS3G4l** [comment]
Not really @343max . Do you want me to add you as the maintainer/owner of the project on PyPI?

**Comment by 343max** [comment]
I guess that would be a good idea.

**Comment by 16BitS3G4l** [comment]
Okay then. @343max What's your username/email on PyPI?

**Pull request merged**
